name: CI/CD flow for production environment

on:
  push:
    branches: ["main"]

env:
  PROJECT: gcp-automated-blog-prod
  REGION: "europe-west4"
  # Image
  IMAGE_NAME: "blog-ai-assistant-aws-tunnel"
  AR_URL: "europe-west4-docker.pkg.dev/gcp-automated-blog-prod/autoblog-prod-gar"

jobs:
  ci:
    permissions:
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_PROD_ENVIRONMENT_SA }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      # CI - Build

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}"
          tags: |
            type=sha,format=short,prefix=

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
